apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-argocd
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-argocd:v0.9.2
  packagePullPolicy: IfNotPresent
  controllerConfigRef:
    name: provider-argocd-controllerconfig
