apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-argocd
  labels:
    app: crossplane
    provider: argocd
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-argocd:v0.9.2
  packagePullPolicy: IfNotPresent
  runtimeConfigRef:
    name: provider-argocd-config
