apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
  namespace: argocd
spec:
  project: control-plane
  source:
    repoURL: https://github.com/platformnow/catalog.git
    targetRevision: main
    path: clusters/bootstrap/cluster-resources
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true