apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: landscape-system
spec:
  destination:
    namespace: landscape-system
    server: https://kubernetes.default.svc
  project: crossplane
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.11.2
    helm:
      parameters:
      - name: "args"
        value: "{--debug,--enable-composition-functions}"
      - name: "xfn.enabled"
        value: "true"
      - name: "xfn.arg"
        value: "{--debug}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
