apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: control-plane
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.14.5
    helm:
      values: |
        args:
          - --debug
          - --enable-environment-configs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
