apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: landscape-system
spec:
  destination:
    namespace: landscape-system
    server: https://kubernetes.default.svc
  project: crossplane
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.13.2
    helm:
      parameters:
#       - name: "xfn.image.tag"
#         value: "v1.11.0-10.g99ce14c1"
      - name: "args[0]"
        value: "--debug"
      - name: "args[1]"
        value: "--enable-composition-functions"
      - name: "xfn.enabled"
        value: "true"
      - name: "xfn.args[0]"
        value: "--debug"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
