apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.13.0
  packagePullPolicy: IfNotPresent
  controllerConfigRef:
    name: provider-helm-controllerconfig
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm
  namespace: landscape-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-helm-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: provider-helm
    namespace: landscape-system
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-helm-controllerconfig
spec:
  serviceAccountName: provider-helm
