apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-helm-config
  labels:
    app: crossplane
    provider: helm
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-helm
  # Add resource limits and requests
  # resources:
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  #   requests:
  #     cpu: 100m