apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
  labels:
    app: crossplane
    provider: helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.20.4
  packagePullPolicy: IfNotPresent
  runtimeConfigRef:
    name: provider-helm-config
